-- MySQL Script generated by MySQL Workbench
-- Wed Jan 13 17:37:58 2016
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema plant
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `plant` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `plant` ;

-- -----------------------------------------------------
-- Table `plant`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plant`.`USER` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_account` VARCHAR(20) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `user_password` VARCHAR(45) NOT NULL,
  `user_head` VARCHAR(100) NULL,
  `user_sex` TINYINT NULL,
  `user_phone` VARCHAR(45) NOT NULL,
  `user_qq` VARCHAR(45) NULL,
  `user_wechat` VARCHAR(45) NULL,
  `user_create_time` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plant`.`BOOK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plant`.`BOOK` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `type_id` INT NOT NULL,
  `book_coin` INT NOT NULL,
  `book_state` TINYINT NOT NULL,
  `book_location` VARCHAR(100) NULL,
  `book_latitude` FLOAT NULL,
  `book_longitude` FLOAT NULL,
  `book_cover` VARCHAR(100) NOT NULL,
  `book_images` TEXT NULL,
  `book_content` TEXT NULL,
  `book_time` DATETIME NOT NULL,
  `book_name` VARCHAR(100) NOT NULL,
  `book_author` VARCHAR(45) NOT NULL,
  `book_publishing_company` VARCHAR(45) NOT NULL,
  `book_publishing_time` DATETIME NULL,
  `book_isbn` VARCHAR(20) NULL,
  PRIMARY KEY (`book_id`),
  INDEX `user_id_fk_book_idx` (`user_id` ASC),
  CONSTRAINT `user_id_fk_book`
    FOREIGN KEY (`user_id`)
    REFERENCES `plant`.`USER` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plant`.`COLLECTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plant`.`COLLECTION` (
  `collection_id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `collection_time` DATETIME NOT NULL,
  PRIMARY KEY (`collection_id`),
  INDEX `user_id_fk_collection_idx` (`user_id` ASC),
  INDEX `book_id_fk_collection_idx` (`book_id` ASC),
  CONSTRAINT `user_id_fk_collection`
    FOREIGN KEY (`user_id`)
    REFERENCES `plant`.`USER` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `book_id_fk_collection`
    FOREIGN KEY (`book_id`)
    REFERENCES `plant`.`BOOK` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plant`.`PRIVILEGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plant`.`PRIVILEGE` (
  `privilege_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `user_coin` INT NULL,
  `user_level` VARCHAR(45) NULL,
  `user_last_time` DATETIME NULL,
  PRIMARY KEY (`privilege_id`),
  INDEX `privilege_user_fk_id_idx` (`user_id` ASC),
  CONSTRAINT `user_id_fk_privilege`
    FOREIGN KEY (`user_id`)
    REFERENCES `plant`.`USER` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plant`.`COMMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plant`.`COMMENT` (
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `comment_user_id` INT NOT NULL,
  `comment_book_id` INT NOT NULL,
  `comment_reply_id` INT NULL,
  `comment_content` TEXT NOT NULL,
  `comment_time` DATETIME NOT NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `book_id_fk_comment_idx` (`comment_book_id` ASC),
  INDEX `user_id_fk_comment_idx` (`comment_user_id` ASC),
  CONSTRAINT `user_id_fk_comment`
    FOREIGN KEY (`comment_user_id`)
    REFERENCES `plant`.`USER` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `book_id_fk_comment`
    FOREIGN KEY (`comment_book_id`)
    REFERENCES `plant`.`BOOK` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
